[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    assetPath = "public"

[[plugins]]
  package = "netlify-plugin-large-media"
  [plugins.inputs]
    base = "/img"
